---
- name: Download InfluxDB (rpm)
  get_url:
    url: "{{ influxdb_mirror }}/influxdb-{{ influxdb_version }}.x86_64.rpm"
    dest: "/opt/influxdb-{{ influxdb_version }}.x86_64.rpm"
  register: download_influxdb_rpm
  until: download_influxdb_rpm is success
  retries: 5
  delay: 2

- name: Install InfluxDB (zypper)
  zypper:
    name: "{{ influxdb_mirror }}/influxdb-{{ influxdb_version }}.x86_64.rpm"
    state: present
  register: install_influxdb
  until: install_influxdb is success
  retries: 5
  delay: 2
