---
- include: install_apt.yml
  when: "ansible_os_family == 'Debian'"

- include: install_rpm.yml
  when: "ansible_os_family == 'RedHat'"

- include: install_zypper.yml
  when: "ansible_os_family == 'Suse'"
