---
- name: Download InfluxDB (rpm)
  get_url:
    url: "{{ influxdb_mirror }}/influxdb-{{ influxdb_version }}.x86_64.rpm"
    dest: "/opt/influxdb-{{ influxdb_version }}.x86_64.rpm"
  register: download_influxdb_rpm
  until: download_influxdb_rpm is success
  retries: 5
  delay: 2

- name: Install InfluxDB (zypper)
  command: "/usr/bin/zypper --quiet --non-interactive --xmlout --no-gpg-check install --type package --auto-agree-with-licenses --no-recommends -- /opt/influxdb-{{ influxdb_version }}.x86_64.rpm"
